### ISSUE TITLE
Bad name for a good project

### ISSUE THREAD

**Issue by olekukonko** [forestgiant/iris#1]
This name chosen `iris` is quite similar to the [iris framework](https://github.com/kataras/iris) that has a bad reputation. 

- http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html
- https://www.reddit.com/r/golang/comments/57tmp1/why_you_should_not_use_iris_for_your_go_projects/

It would be nice for you to consider one of the followings for PR purpose 

- Change of Name
-  A good suffix to differentiate it from the other Iris project

What do you think?

**Comment by jessicaelle** [comment]
Thanks for bringing this to our attention. I've forwarded the links you provided to the team and we're planning to discuss it thoroughly. Thanks again for checking out our platform - we're happy you like it!

**Comment by ScottMansfield** [comment]
I think this project could make the name iris great again
